name: SimpleHubDelay
api: 4.0.0
version: 0.2
main: BeeAZZ\SimpleHubDelay\Main
author: BeeAZZ

commands:
 hub:
  description: Teleport To Hub
  permission: hub.command
permissions:
 hub.command:
  default: true
